git_cmd = "/usr/bin/git"
user_refact_msg = "user refactor (will be deleted)"
unpushed_commit_folder = "hooks/.tmp_refac/"
unpushed_commit_file_name = "unpushed_commit"
unpushed_commit_file_status = "status"
